### PR TITLE
Add gateway configuration for RU_864_870 band (Russia)

### PR DESCRIPTION
**Pull request by belovictor**
This pull request adds a gateway configuration for RU_864_870 band (Russia) as discussed here: https://www.thethingsnetwork.org/forum/t/implementing-a-new-frequency-plan-in-ttn/16803

### CODE REVIEW

**Comment by htdvisser** [comment]
Here's what this channel plan would look like:

screen shot 2018-08-14 at 09 09 44

What's the reason for not keeping the channels a bit closer together?

**Comment by belovictor** [comment]
This channel plan is a product of a working group under local IOT association (iotas.ru) where all local LoRaWAN networks participated. It is based on local regulation and testing of SX1301 performance for this regulation and is approved by local regulation office and is currently deployed by all LoRaWAN networks locally.

**Comment by htdvisser** [comment]
Fair enough. @jpmeijers could you also take a look at this?

**Comment by jpmeijers** [comment]
@belovictor explained to me why the channels need to be where they are here, and it is due to their local regulations. 

The format of the file looks correct to me.

*APPROVED*

**Comment by belovictor** [comment]
Thanks. Just for the history:
There are 2 documents which were issued by local regulator for 868 ISM. The first one permits usage of 864-865 MHz with peak power of 25 mW and with either 0.1% duty cycle or LBT. This band have a limitation - it can’t be used near airports. The second one permits usage of 868.7-869.2 MHz with peak power of 25 mW without dutycycle limitation. Those 2 documents are 08-24-01-001 from 28.04.2008  and 07-20-03-001  from 07.05.2007  which was then prolonged with 17-40-06-2 from 10.03.2017, closure 21.

**Review by htdvisser — APPROVED** [review]

**Pull request merged**
