### PR TITLE
Add links for LBT, non LBT AS regions

### LINKED ISSUE #28: lbt_cfg prevents some gateways from operating
For AS2, Japan requires LBT. But Taiwan does not.

Currently, the as2 config includes LBT overrides. This means that gateways in Taiwan without LBT support in hardware can't use the as2 config, even though they're otherwise fine.  

Please consider further splitting for AS2 with and without LBT.

(I also note that AS1 always enforces LBT, and I'm not sure that this is needed in every country.)

### PR DESCRIPTION
**Pull request by terrillmoore**
Fix #28 by creating lbt and non-lbt versions of files, and (some but not all) countries needing one or the other.

### CODE REVIEW

**Comment by terrillmoore** [comment]
Using a Posix timezone-like approach. Files are hardlinks (and show up as such on my WIndows system under git bash, but this should perhaps be checked).

**Review by johanstokking — COMMENTED** [review]
Thanks for submitting @terrillmoore !

Those hard links didn't make it.

I would go for the per-country approach, and keep references in a subdirectory so we can pick from there if we add a new country that we can base on an existing frequency plan.

**Comment by egourlao** [comment]
It doesn't seem that Git supports symlinks at all: https://stackoverflow.com/questions/954560/how-does-git-handle-symbolic-links I agree with @johanstokking on going for an approach with less files, and more documentation.

As an FYI, V3's new lightweight [frequency plans format](https://github.com/TheThingsNetwork/gateway-conf/tree/yaml-master) supports extending another frequency plan, which means we'll have less verbose files for this kind of cases.

**Comment by terrillmoore** [comment]
OK, I'll look at revising and resubmitting. May take a few days, got a bit of a backlog here to get through.

**Comment by johanstokking** [comment]
@terrillmoore we have a new repository for V3 frequency plans: https://github.com/TheThingsNetwork/lorawan-frequency-plans. It allows you to easily add frequency plans with a `base-id`, so you can enable listen-before-talk on selected plans. Please re-open this issue there if this is still relevant for you.

**Pull request closed without merging**
